# No idea why this line is not executing. Random byte at the start?
@echo off
cls
title Updating...
echo Waiting 3 seconds to ensure process is closed...
powershell start-sleep 3
echo Copying update files over the old version of the application...
xcopy /s /y ".\updateTemp" ".\"
echo done!
ren SLWModLoader.log SLWModLoader_prev.log
sleep 1
echo Starting application...
start SLWModLoader.exe