//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HedgeModManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HedgeModManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace HMMCodes
        ///{
        ///    public enum Keys
        ///    {
        ///        /// &lt;summary&gt;
        ///        ///  The bit mask to extract a key code from a key value.
        ///        /// &lt;/summary&gt;
        ///        KeyCode = 0x0000FFFF,
        ///
        ///        /// &lt;summary&gt;
        ///        ///  The bit mask to extract modifiers from a key value.
        ///        /// &lt;/summary&gt;
        ///        Modifiers = unchecked((int)0xFFFF0000),
        ///
        ///        /// &lt;summary&gt;
        ///        ///  No key pressed.
        ///        /// &lt;/summary&gt;
        ///        None = 0x00,
        ///
        ///        /// &lt;summary&gt;
        ///        ///  The left mouse button.
        ///        / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Runtime.InteropServices;
        ///
        ///namespace HMMCodes
        ///{
        ///    public static unsafe class MemoryService
        ///    {
        ///        [DllImport(&quot;kernel32.dll&quot;)]
        ///        public static extern bool VirtualProtect(IntPtr lpAddress,
        ///                IntPtr dwSize, uint flNewProtect, out uint lpflOldProtect);
        ///
        ///        [DllImport(&quot;kernel32.dll&quot;, CharSet = CharSet.Auto)]
        ///        public static extern IntPtr GetModule [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MemoryService {
            get {
                return ResourceManager.GetString("MemoryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_CSharp {
            get {
                object obj = ResourceManager.GetObject("Microsoft_CSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] netstandard {
            get {
                object obj = ResourceManager.GetObject("netstandard", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
